### PR TITLE
fix: Add wallet and global switch

### PR DESCRIPTION
**Pull request by richtera**
### Ticket ID

https://app.clickup.com/t/2645698/DEV-8018

### Description

Add wallet and global switch.
The site will by default act as global.
For localhost and pages.dev it will add a cookie which can be flipped
by adding ?wallet or ?global to the URL.
In production it will look at https://universalprofile.cloud and https://wallet.universalprofile.cloud.
The home page for ?global is a temporary copy from universalprofile.cloud which is not fully styled
and doesn't have algolia built in yet.

### CODE REVIEW

**Comment by Hugoo** [comment]
Task linked: [DEV-8018 Allow wallet dApp to detect where it's running](https://app.clickup.com/t/2645698/DEV-8018)

**Review by dzbo — COMMENTED** [review]
There is planned wallet landing page that I'm working on atm, so we need to put this search in other place

**Comment by Hugoo** [comment]
linked to: https://github.com/lukso-network/wallet.universalprofile.cloud/pull/36

**Comment by richtera** [comment]
> There is planned wallet landing page that I'm working on atm, so we need to put this search in other place

You can still have two home pages. The significant thing is that we need the profile pages on the universalprofile.cloud site

**Comment by dzbo** [comment]
@richtera can you adjust the PR? I think we can remove all search UI part since we plan to use [Algolia](https://www.algolia.com/)

**Comment by dzbo** [comment]
Closing since we build separate indexer project for this

**Pull request closed without merging**
