### PR TITLE
fix: Convert object data for `links` and `tags` from Algolia into array

### PR DESCRIPTION
**Pull request by dzbo**
### Ticket ID

[DEV-9583](https://app.clickup.com/t/2645698/DEV-9583)

### Description

- since Algolia return data as objects we need to convert into array
- LSP8 conversion will be in other PR

### CODE REVIEW

**Comment by Hugoo** [comment]
Task linked: [DEV-9585 Fetch LSP8 data from Algolia](https://app.clickup.com/t/2645698/DEV-9585)

**Comment by Hugoo** [comment]
Task linked: [DEV-9583 Fetch profile data from Algolia](https://app.clickup.com/t/2645698/DEV-9583)

**Comment by dzbo** [comment]
> That is something we could do inside of the api layer. It's hard to do inside of golang I think. Let me know.

That would be great since I need to parse every data that should be array, atm response is not aligned with our types.

**Comment by richtera** [comment]
> > That is something we could do inside of the api layer. It's hard to do inside of golang I think. Let me know.
> 
> That would be great since I need to parse every data that should be array, atm response is not aligned with our types.

Added.

**Comment by dzbo** [comment]
> > > That is something we could do inside of the api layer. It's hard to do inside of golang I think. Let me know.
> > 
> > 
> > That would be great since I need to parse every data that should be array, atm response is not aligned with our types.
> 
> Added.

nice! let me put that in draft then so I can adjust.

**Comment by dzbo** [comment]
No needed anymore since Algolia pass now proper format of the data.

**Pull request closed without merging**
