### PR TITLE
feat: fetch LSP7 data from Algolia

### PR DESCRIPTION
**Pull request by dzbo**
### Ticket ID

[DEV-9584](https://app.clickup.com/t/2645698/DEV-9584)

### Description

- fetch LSP7 token metadata from Algolia

### CODE REVIEW

**Comment by Hugoo** [comment]
Task linked: [DEV-9584 Fetch LSP7 data from Algolia](https://app.clickup.com/t/2645698/DEV-9584)

**Comment by Hugoo** [comment]
Task linked: [DEV-9583 Fetch profile data from Algolia](https://app.clickup.com/t/2645698/DEV-9583)

**Review by Hugoo — COMMENTED** [review]
Addind a warning here on the cost increases!

Algolia charges a lot 0.50cts per 1000 rq!

I'm afk now but I'll check further

**Review by richtera — APPROVED** [review]

**Review by doubleppereira — APPROVED** [review]

**Comment by Hugoo** [comment]
> > Addind a warning here on the cost increases!
> > Algolia charges a lot 0.50cts per 1000 rq!
> > I'm afk now but I'll check further
> 
> I still think it's the best option right now. Making a lot of getData calls to retrieve this data is also expensive and makes the code much more complicated. Since we already have a solution for the indexer posting it's data elsewhere I think this will be resolved very soon as well.

> getData calls to retrieve this data is also expensive

How much? The RPC doesnt charge per request. It adds load on our RPC - or Gateway one.

Then let's push the new API faster

If we release this tomorrow we will get charged thousands a week.f

**Comment by dzbo** [comment]
> Addind a warning here on the cost increases!
> 
> Algolia charges a lot 0.50cts per 1000 rq!
> 
> I'm afk now but I'll check further

Querying RPC is not valid solution atm. We make hundreds of requests meaning none of the providers work for us due to limits. Algolia seem to be best solution but yes it will increase the cost. Although we don't use it directly but proxy throught our API and this allow us to implement caching for instance and lower costs too.

**Pull request merged**
